-- =============================================================================
-- OpsFlow · docs/schema/target-v1.sql · TARGET V1 SCHEMA (reference design)
--
-- This file is never applied directly. Each phase writes its own migration in
-- packages/db/migrations from the relevant part of this file, adjusting it to
-- what building the feature has taught you. Target: PostgreSQL 17+.
--
-- Conventions
--   * Primary keys are UUIDv7 generated by the app (time-ordered). The
--     gen_random_uuid() defaults are only a fallback for scripts and seeds.
--   * Every tenant-owned table has org_id, a UNIQUE (org_id, id), and composite
--     foreign keys (org_id, x_id) so a row can never point into another tenant.
--   * Instants are timestamptz (UTC). Calendar days (leave, holidays) are date.
--   * Day quantities are numeric(5,1) in steps of 0.5. Never float.
--   * Status columns are text + CHECK, not enums: easier to evolve.
--   * Editable rows carry version (optimistic concurrency, bumped by the app).
-- =============================================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS citext;      -- case-insensitive email
CREATE EXTENSION IF NOT EXISTS btree_gist;  -- = inside GiST exclusion constraints
CREATE EXTENSION IF NOT EXISTS pg_trgm;     -- fuzzy search on names and titles

-- -----------------------------------------------------------------------------
-- Helper functions
-- -----------------------------------------------------------------------------

-- The tenant for the current transaction, set by withTenant():
--   SELECT set_config('app.org_id', $1, true);
-- NULLIF guards against a session where the setting exists but is empty.
CREATE FUNCTION app_org_id() RETURNS uuid
LANGUAGE sql STABLE PARALLEL SAFE AS $$
  SELECT NULLIF(current_setting('app.org_id', true), '')::uuid
$$;

-- The signed-in user for the current transaction, set by withUser()/withTenant():
--   SELECT set_config('app.user_id', $1, true);
-- Lets a user read their own memberships across orgs (login, org switcher)
-- without any role that bypasses RLS.
CREATE FUNCTION app_user_id() RETURNS uuid
LANGUAGE sql STABLE PARALLEL SAFE AS $$
  SELECT NULLIF(current_setting('app.user_id', true), '')::uuid
$$;

CREATE FUNCTION set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END $$;

-- Append-only tables reject UPDATE for every role. DELETE is revoked from the
-- application roles instead, so cascading org deletion still works.
CREATE FUNCTION forbid_update() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION '% is append-only', TG_TABLE_NAME
    USING ERRCODE = 'insufficient_privilege';
END $$;

-- Rejects time zone names Postgres does not know ('Mars/Base').
CREATE FUNCTION validate_org_timezone() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  PERFORM now() AT TIME ZONE NEW.timezone;
  RETURN NEW;
END $$;

-- =============================================================================
-- 1. Identity (global, not tenant-scoped, no RLS)
-- =============================================================================

CREATE TABLE users (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email             citext NOT NULL UNIQUE CHECK (email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
  password_hash     text,                       -- argon2id; NULL for Google-only accounts
  display_name      text NOT NULL CHECK (length(btrim(display_name)) BETWEEN 1 AND 120),
  email_verified_at timestamptz,
  last_login_at     timestamptz,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE user_identities (                 -- external sign-in (Phase 6)
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  provider         text NOT NULL CHECK (provider IN ('google')),
  provider_subject text NOT NULL,
  created_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (provider, provider_subject),
  UNIQUE (user_id, provider)
);

CREATE TABLE sessions (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash   bytea NOT NULL UNIQUE CHECK (octet_length(token_hash) = 32),  -- SHA-256 of the cookie token
  created_at   timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  expires_at   timestamptz NOT NULL,
  revoked_at   timestamptz,
  ip           inet,
  user_agent   text CHECK (length(user_agent) <= 512),
  CHECK (expires_at > created_at)
);
CREATE INDEX sessions_user_live_idx ON sessions (user_id) WHERE revoked_at IS NULL;
CREATE INDEX sessions_expires_idx   ON sessions (expires_at);  -- cleanup job

CREATE TABLE email_tokens (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  purpose    text NOT NULL CHECK (purpose IN ('verify_email', 'reset_password')),
  token_hash bytea NOT NULL UNIQUE CHECK (octet_length(token_hash) = 32),
  expires_at timestamptz NOT NULL,
  used_at    timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX email_tokens_user_idx ON email_tokens (user_id, purpose) WHERE used_at IS NULL;

-- =============================================================================
-- 2. Organization and people
-- =============================================================================

CREATE TABLE organizations (
  id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name                   text NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 120),
  slug                   text NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9][a-z0-9-]{1,38}[a-z0-9]$'),
  timezone               text NOT NULL DEFAULT 'Asia/Kolkata',
  working_days           smallint[] NOT NULL DEFAULT '{1,2,3,4,5}'   -- ISO weekdays, 1 = Monday
                         CHECK (working_days <@ '{1,2,3,4,5,6,7}'::smallint[]
                                AND cardinality(working_days) BETWEEN 1 AND 7),
  leave_year_start_month smallint NOT NULL DEFAULT 1 CHECK (leave_year_start_month BETWEEN 1 AND 12),
  logo_file_id           uuid,                  -- FK added after files exists
  created_at             timestamptz NOT NULL DEFAULT now(),
  updated_at             timestamptz NOT NULL DEFAULT now()
);
CREATE TRIGGER organizations_timezone_chk BEFORE INSERT OR UPDATE OF timezone ON organizations
  FOR EACH ROW EXECUTE FUNCTION validate_org_timezone();

CREATE TABLE departments (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id     uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name       text NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 80),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (org_id, id)
);
CREATE UNIQUE INDEX departments_name_uq ON departments (org_id, lower(name));

CREATE TABLE memberships (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id         uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  user_id        uuid NOT NULL REFERENCES users(id),
  role           text NOT NULL CHECK (role IN ('owner', 'admin', 'manager', 'employee')),
  status         text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'deactivated')),
  employee_code  text CHECK (length(btrim(employee_code)) BETWEEN 1 AND 32),
  job_title      text CHECK (length(job_title) <= 120),
  phone          text CHECK (length(phone) <= 32),
  department_id  uuid,
  manager_id     uuid,                          -- reporting line; leave approvals follow it
  joined_on      date,
  deactivated_at timestamptz,
  version        integer NOT NULL DEFAULT 1,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  UNIQUE (org_id, id),
  UNIQUE (org_id, user_id),
  CHECK (manager_id <> id),
  CHECK ((status = 'deactivated') = (deactivated_at IS NOT NULL)),
  CHECK (role <> 'owner' OR status = 'active'),
  FOREIGN KEY (org_id, department_id) REFERENCES departments (org_id, id) ON DELETE SET NULL (department_id),
  FOREIGN KEY (org_id, manager_id)    REFERENCES memberships (org_id, id)
);
CREATE UNIQUE INDEX memberships_employee_code_uq ON memberships (org_id, lower(employee_code)) WHERE employee_code IS NOT NULL;
CREATE UNIQUE INDEX memberships_one_owner_uq     ON memberships (org_id) WHERE role = 'owner';
CREATE INDEX memberships_reports_idx  ON memberships (org_id, manager_id) WHERE status = 'active';
CREATE INDEX memberships_user_idx     ON memberships (user_id);
CREATE INDEX memberships_dept_idx     ON memberships (org_id, department_id);
-- Reporting cycles (A manages B manages A) are rejected in the service with a
-- recursive CTE before the update; a trigger version is a good later exercise.

CREATE TABLE teams (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id        uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  department_id uuid,
  name          text NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 80),
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (org_id, id),
  FOREIGN KEY (org_id, department_id) REFERENCES departments (org_id, id) ON DELETE SET NULL (department_id)
);
CREATE UNIQUE INDEX teams_name_uq ON teams (org_id, lower(name));

CREATE TABLE team_members (
  org_id        uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  team_id       uuid NOT NULL,
  membership_id uuid NOT NULL,
  is_lead       boolean NOT NULL DEFAULT false,
  added_at      timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (team_id, membership_id),
  FOREIGN KEY (org_id, team_id)       REFERENCES teams (org_id, id)       ON DELETE CASCADE,
  FOREIGN KEY (org_id, membership_id) REFERENCES memberships (org_id, id) ON DELETE CASCADE
);
CREATE INDEX team_members_member_idx ON team_members (org_id, membership_id);

CREATE TABLE invitations (
  id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id                 uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  email                  citext NOT NULL,
  role                   text NOT NULL CHECK (role IN ('admin', 'manager', 'employee')),  -- owner only by transfer
  department_id          uuid,
  team_id                uuid,
  manager_id             uuid,
  invited_by             uuid NOT NULL,
  token_hash             bytea NOT NULL UNIQUE CHECK (octet_length(token_hash) = 32),
  expires_at             timestamptz NOT NULL,
  accepted_at            timestamptz,
  accepted_membership_id uuid,
  revoked_at             timestamptz,
  created_at             timestamptz NOT NULL DEFAULT now(),
  CHECK (accepted_at IS NULL OR revoked_at IS NULL),
  CHECK ((accepted_at IS NULL) = (accepted_membership_id IS NULL)),
  FOREIGN KEY (org_id, department_id)          REFERENCES departments (org_id, id) ON DELETE SET NULL (department_id),
  FOREIGN KEY (org_id, team_id)                REFERENCES teams (org_id, id)       ON DELETE SET NULL (team_id),
  FOREIGN KEY (org_id, manager_id)             REFERENCES memberships (org_id, id),
  FOREIGN KEY (org_id, invited_by)             REFERENCES memberships (org_id, id),
  FOREIGN KEY (org_id, accepted_membership_id) REFERENCES memberships (org_id, id)
);
-- One open invitation per email per org; "resend" rotates the token on the same row.
CREATE UNIQUE INDEX invitations_open_uq ON invitations (org_id, email) WHERE accepted_at IS NULL AND revoked_at IS NULL;

-- Per-org human-readable numbers (TASK-1024, TKT-208). See the blueprint, section 7.
CREATE TABLE org_counters (
  org_id     uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  scope      text NOT NULL CHECK (scope IN ('task', 'ticket')),
  next_value bigint NOT NULL CHECK (next_value > 0),
  PRIMARY KEY (org_id, scope)
);

-- =============================================================================
-- 3. Files (bytes live in S3; this is the metadata and access record)
-- =============================================================================

CREATE TABLE files (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id        uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  uploaded_by   uuid NOT NULL,
  storage_key   text NOT NULL UNIQUE,         -- orgs/{org_id}/{file_id}; never the user's file name
  original_name text NOT NULL CHECK (length(original_name) BETWEEN 1 AND 255),
  mime_type     text NOT NULL CHECK (mime_type ~ '^[a-z]+/[a-z0-9.+-]+$'),
  size_bytes    bigint NOT NULL CHECK (size_bytes BETWEEN 1 AND 26214400),  -- 25 MB cap
  sha256        bytea CHECK (octet_length(sha256) = 32),
  status        text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'uploaded', 'clean', 'infected')),
  created_at    timestamptz NOT NULL DEFAULT now(),
  uploaded_at   timestamptz,
  UNIQUE (org_id, id),
  CHECK (status = 'pending' OR uploaded_at IS NOT NULL),
  FOREIGN KEY (org_id, uploaded_by) REFERENCES memberships (org_id, id)
);
CREATE INDEX files_pending_idx ON files (created_at) WHERE status = 'pending';  -- sweep abandoned uploads

ALTER TABLE organizations
  ADD CONSTRAINT organizations_logo_fk FOREIGN KEY (id, logo_file_id)
  REFERENCES files (org_id, id) ON DELETE SET NULL (logo_file_id);

-- =============================================================================
-- 4. Leave and WFH
-- =============================================================================

CREATE TABLE leave_types (
  id                           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id                       uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name                         text NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 60),
  category                     text NOT NULL CHECK (category IN ('leave', 'wfh')),
  deducts_balance              boolean NOT NULL,
  annual_quota                 numeric(5,1) CHECK (annual_quota >= 0),          -- NULL = no limit
  allow_half_day               boolean NOT NULL DEFAULT true,
  document_required_after_days smallint CHECK (document_required_after_days >= 0),
  carry_forward_max            numeric(5,1) NOT NULL DEFAULT 0 CHECK (carry_forward_max >= 0),
  is_active                    boolean NOT NULL DEFAULT true,
  created_at                   timestamptz NOT NULL DEFAULT now(),
  updated_at                   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (org_id, id),
  CHECK (category = 'leave' OR NOT deducts_balance),         -- WFH never uses a balance
  CHECK (NOT deducts_balance OR annual_quota IS NOT NULL)    -- a balance needs a quota
);
CREATE UNIQUE INDEX leave_types_name_uq ON leave_types (org_id, lower(name));

CREATE TABLE holidays (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id       uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  holiday_date date NOT NULL,
  name         text NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 80),
  created_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (org_id, holiday_date)
);

CREATE TABLE leave_requests (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id        uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  member_id     uuid NOT NULL,
  leave_type_id uuid NOT NULL,
  start_date    date NOT NULL,
  end_date      date NOT NULL,
  start_half    text NOT NULL DEFAULT 'full' CHECK (start_half IN ('full', 'first', 'second')),
  end_half      text NOT NULL DEFAULT 'full' CHECK (end_half   IN ('full', 'first', 'second')),
  days          numeric(5,1) NOT NULL CHECK (days > 0 AND days * 2 = trunc(days * 2)),  -- computed once at submit
  reason        text CHECK (length(reason) <= 1000),
  status        text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'cancelled')),
  approver_id   uuid,                           -- snapshot of the manager at submission
  decided_by    uuid,
  decided_at    timestamptz,
  decision_note text CHECK (length(decision_note) <= 1000),
  cancelled_at  timestamptz,
  version       integer NOT NULL DEFAULT 1,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (org_id, id),
  CHECK (end_date >= start_date),
  CHECK (end_date - start_date < 366),
  -- One day: both halves agree (full/full, first/first, second/second).
  CHECK (start_date <> end_date OR start_half = end_half),
  -- Several days: may start at midday and end at midday, never the reverse.
  CHECK (start_date = end_date OR (start_half IN ('full', 'second') AND end_half IN ('full', 'first'))),
  CHECK (status NOT IN ('approved', 'rejected') OR decided_at IS NOT NULL),
  CHECK (status <> 'rejected' OR decision_note IS NOT NULL),
  CHECK ((status = 'cancelled') = (cancelled_at IS NOT NULL)),
  CHECK (decided_by IS NULL OR decided_by <> member_id),     -- nobody approves their own leave
  FOREIGN KEY (org_id, member_id)     REFERENCES memberships (org_id, id),
  FOREIGN KEY (org_id, leave_type_id) REFERENCES leave_types (org_id, id),
  FOREIGN KEY (org_id, approver_id)   REFERENCES memberships (org_id, id),
  FOREIGN KEY (org_id, decided_by)    REFERENCES memberships (org_id, id),
  -- A member can never hold two live requests touching the same day.
  -- Consequence (deliberate in V1): a morning and an afternoon request on one date conflict.
  CONSTRAINT leave_requests_no_overlap EXCLUDE USING gist (
    member_id WITH =,
    daterange(start_date, end_date, '[]') WITH &&
  ) WHERE (status IN ('pending', 'approved'))
);
CREATE INDEX leave_requests_inbox_idx  ON leave_requests (org_id, approver_id, created_at) WHERE status = 'pending';
CREATE INDEX leave_requests_member_idx ON leave_requests (org_id, member_id, start_date DESC);
CREATE INDEX leave_requests_range_idx  ON leave_requests USING gist (org_id, daterange(start_date, end_date, '[]'))
  WHERE status IN ('pending', 'approved');                     -- calendar and team-availability queries

-- How a request's days split across leave years, computed once at submission.
-- A request from 30 Dec to 2 Jan has two rows; approval locks and checks each
-- year's balance, then writes one debit per row. Rows always sum to
-- leave_requests.days (checked at commit by leave_allocations_sum_chk).
CREATE TABLE leave_request_allocations (
  org_id      uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  request_id  uuid NOT NULL,
  period_year smallint NOT NULL CHECK (period_year BETWEEN 2000 AND 2100),
  days        numeric(5,1) NOT NULL CHECK (days > 0 AND days * 2 = trunc(days * 2)),
  PRIMARY KEY (request_id, period_year),
  UNIQUE (org_id, request_id, period_year),
  FOREIGN KEY (org_id, request_id) REFERENCES leave_requests (org_id, id) ON DELETE CASCADE
);

CREATE FUNCTION check_leave_allocations() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
  rid       uuid;
  req_days  numeric;
  allocated numeric;
BEGIN
  IF TG_TABLE_NAME = 'leave_requests' THEN
    rid := NEW.id;
  ELSIF TG_OP = 'DELETE' THEN
    rid := OLD.request_id;
  ELSE
    rid := NEW.request_id;
  END IF;

  SELECT days INTO req_days FROM leave_requests WHERE id = rid;
  IF NOT FOUND THEN
    RETURN NULL;                      -- request deleted (org deletion cascade)
  END IF;
  SELECT coalesce(sum(days), 0) INTO allocated FROM leave_request_allocations WHERE request_id = rid;
  IF allocated <> req_days THEN
    RAISE EXCEPTION 'leave request % allocates % of % days', rid, allocated, req_days
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NULL;
END $$;

CREATE CONSTRAINT TRIGGER leave_allocations_sum_chk
  AFTER INSERT OR UPDATE OR DELETE ON leave_request_allocations
  DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION check_leave_allocations();
CREATE CONSTRAINT TRIGGER leave_requests_allocations_chk
  AFTER INSERT OR UPDATE OF days ON leave_requests
  DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION check_leave_allocations();

-- Balance = SUM(delta) per member, type and leave year. Never updated, never deleted.
CREATE TABLE leave_ledger (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id        uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  member_id     uuid NOT NULL,
  leave_type_id uuid NOT NULL,
  period_year   smallint NOT NULL CHECK (period_year BETWEEN 2000 AND 2100),  -- leave year it counts against
  kind          text NOT NULL CHECK (kind IN ('accrual', 'carry_forward', 'debit', 'reversal', 'adjustment')),
  delta         numeric(5,1) NOT NULL CHECK (delta <> 0 AND delta * 2 = trunc(delta * 2)),
  request_id    uuid,
  note          text CHECK (length(note) <= 500),
  created_by    uuid,                           -- NULL = system job
  created_at    timestamptz NOT NULL DEFAULT now(),
  CHECK ((kind IN ('debit', 'reversal')) = (request_id IS NOT NULL)),
  CHECK (kind <> 'debit' OR delta < 0),
  CHECK (kind NOT IN ('accrual', 'carry_forward', 'reversal') OR delta > 0),
  CHECK (kind <> 'adjustment' OR (note IS NOT NULL AND created_by IS NOT NULL)),  -- manual changes are explained
  -- A request spanning two leave years gets one debit per year, never two in the same year.
  UNIQUE (request_id, kind, period_year),
  FOREIGN KEY (org_id, member_id)     REFERENCES memberships (org_id, id),
  FOREIGN KEY (org_id, leave_type_id) REFERENCES leave_types (org_id, id),
  FOREIGN KEY (org_id, request_id)    REFERENCES leave_requests (org_id, id),
  -- A debit or reversal can only hit a year the request was allocated to.
  FOREIGN KEY (org_id, request_id, period_year)
    REFERENCES leave_request_allocations (org_id, request_id, period_year),
  FOREIGN KEY (org_id, created_by)    REFERENCES memberships (org_id, id)
);
-- A retried accrual or carry-forward job cannot grant the same year twice.
CREATE UNIQUE INDEX leave_ledger_one_accrual_uq ON leave_ledger (member_id, leave_type_id, period_year, kind)
  WHERE kind IN ('accrual', 'carry_forward');
CREATE INDEX leave_ledger_balance_idx ON leave_ledger (org_id, member_id, leave_type_id, period_year) INCLUDE (delta);
CREATE TRIGGER leave_ledger_append_only BEFORE UPDATE ON leave_ledger
  FOR EACH ROW EXECUTE FUNCTION forbid_update();

CREATE TABLE leave_request_attachments (
  org_id     uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  request_id uuid NOT NULL,
  file_id    uuid NOT NULL,
  added_at   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (request_id, file_id),
  FOREIGN KEY (org_id, request_id) REFERENCES leave_requests (org_id, id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, file_id)    REFERENCES files (org_id, id)
);

-- =============================================================================
-- 5. Tasks
-- =============================================================================

CREATE TABLE tasks (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id         uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  number         integer NOT NULL CHECK (number > 0),
  title          text NOT NULL CHECK (length(btrim(title)) BETWEEN 1 AND 200),
  description    text CHECK (length(description) <= 20000),
  status         text NOT NULL DEFAULT 'todo' CHECK (status IN ('todo', 'in_progress', 'blocked', 'done', 'cancelled')),
  priority       text NOT NULL DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
  assignee_id    uuid,
  created_by     uuid NOT NULL,
  team_id        uuid,
  due_at         timestamptz,
  blocked_reason text CHECK (length(blocked_reason) <= 500),
  completed_at   timestamptz,
  archived_at    timestamptz,
  version        integer NOT NULL DEFAULT 1,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  search         tsvector GENERATED ALWAYS AS (
                   to_tsvector('simple'::regconfig, title || ' ' || coalesce(description, ''))
                 ) STORED,
  UNIQUE (org_id, id),
  UNIQUE (org_id, number),
  CHECK ((status = 'done') = (completed_at IS NOT NULL)),
  CHECK (status <> 'blocked' OR blocked_reason IS NOT NULL),
  FOREIGN KEY (org_id, assignee_id) REFERENCES memberships (org_id, id),
  FOREIGN KEY (org_id, created_by)  REFERENCES memberships (org_id, id),
  FOREIGN KEY (org_id, team_id)     REFERENCES teams (org_id, id) ON DELETE SET NULL (team_id)
);
CREATE INDEX tasks_assignee_open_idx ON tasks (org_id, assignee_id, due_at)
  WHERE status NOT IN ('done', 'cancelled') AND archived_at IS NULL;
CREATE INDEX tasks_team_status_idx   ON tasks (org_id, team_id, status) WHERE archived_at IS NULL;
CREATE INDEX tasks_keyset_idx        ON tasks (org_id, created_at DESC, id DESC);
CREATE INDEX tasks_due_idx           ON tasks (org_id, due_at) WHERE status NOT IN ('done', 'cancelled') AND due_at IS NOT NULL;
CREATE INDEX tasks_search_idx        ON tasks USING gin (search);
CREATE INDEX tasks_title_trgm_idx    ON tasks USING gin (title gin_trgm_ops);

CREATE TABLE task_comments (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id     uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  task_id    uuid NOT NULL,
  author_id  uuid NOT NULL,
  body       text NOT NULL CHECK (length(btrim(body)) BETWEEN 1 AND 10000),
  created_at timestamptz NOT NULL DEFAULT now(),
  edited_at  timestamptz,
  deleted_at timestamptz,                       -- soft delete keeps thread positions stable
  FOREIGN KEY (org_id, task_id)   REFERENCES tasks (org_id, id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, author_id) REFERENCES memberships (org_id, id)
);
CREATE INDEX task_comments_task_idx ON task_comments (org_id, task_id, created_at);

CREATE TABLE task_attachments (
  org_id   uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  task_id  uuid NOT NULL,
  file_id  uuid NOT NULL,
  added_by uuid NOT NULL,
  added_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (task_id, file_id),
  FOREIGN KEY (org_id, task_id)  REFERENCES tasks (org_id, id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, file_id)  REFERENCES files (org_id, id),
  FOREIGN KEY (org_id, added_by) REFERENCES memberships (org_id, id)
);

-- =============================================================================
-- 6. Tickets
-- =============================================================================

CREATE TABLE ticket_categories (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id           uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name             text NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 60),
  handling_team_id uuid NOT NULL,              -- this team's members work the queue
  is_active        boolean NOT NULL DEFAULT true,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (org_id, id),
  FOREIGN KEY (org_id, handling_team_id) REFERENCES teams (org_id, id)
);
CREATE UNIQUE INDEX ticket_categories_name_uq ON ticket_categories (org_id, lower(name));

CREATE TABLE tickets (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id       uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  number       integer NOT NULL CHECK (number > 0),
  category_id  uuid NOT NULL,
  requester_id uuid NOT NULL,
  assignee_id  uuid,
  title        text NOT NULL CHECK (length(btrim(title)) BETWEEN 1 AND 200),
  description  text CHECK (length(description) <= 20000),
  status       text NOT NULL DEFAULT 'open'
               CHECK (status IN ('open', 'assigned', 'in_progress', 'waiting', 'resolved', 'closed')),
  priority     text NOT NULL DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
  resolved_at  timestamptz,
  closed_at    timestamptz,
  version      integer NOT NULL DEFAULT 1,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  search       tsvector GENERATED ALWAYS AS (
                 to_tsvector('simple'::regconfig, title || ' ' || coalesce(description, ''))
               ) STORED,
  UNIQUE (org_id, id),
  UNIQUE (org_id, number),
  CHECK (status NOT IN ('assigned', 'in_progress', 'waiting') OR assignee_id IS NOT NULL),
  CHECK ((status IN ('resolved', 'closed')) = (resolved_at IS NOT NULL)),
  CHECK ((status = 'closed') = (closed_at IS NOT NULL)),
  FOREIGN KEY (org_id, category_id)  REFERENCES ticket_categories (org_id, id),
  FOREIGN KEY (org_id, requester_id) REFERENCES memberships (org_id, id),
  FOREIGN KEY (org_id, assignee_id)  REFERENCES memberships (org_id, id)
);
CREATE INDEX tickets_queue_idx     ON tickets (org_id, category_id, status, created_at);
CREATE INDEX tickets_requester_idx ON tickets (org_id, requester_id, created_at DESC);
CREATE INDEX tickets_assignee_idx  ON tickets (org_id, assignee_id, status) WHERE status NOT IN ('resolved', 'closed');
CREATE INDEX tickets_search_idx    ON tickets USING gin (search);

CREATE TABLE ticket_comments (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id      uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  ticket_id   uuid NOT NULL,
  author_id   uuid NOT NULL,
  body        text NOT NULL CHECK (length(btrim(body)) BETWEEN 1 AND 10000),
  is_internal boolean NOT NULL DEFAULT false,  -- handler-only note, hidden from the requester
  created_at  timestamptz NOT NULL DEFAULT now(),
  edited_at   timestamptz,
  deleted_at  timestamptz,
  FOREIGN KEY (org_id, ticket_id) REFERENCES tickets (org_id, id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, author_id) REFERENCES memberships (org_id, id)
);
CREATE INDEX ticket_comments_ticket_idx ON ticket_comments (org_id, ticket_id, created_at);

CREATE TABLE ticket_attachments (
  org_id    uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  ticket_id uuid NOT NULL,
  file_id   uuid NOT NULL,
  added_by  uuid NOT NULL,
  added_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (ticket_id, file_id),
  FOREIGN KEY (org_id, ticket_id) REFERENCES tickets (org_id, id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, file_id)   REFERENCES files (org_id, id),
  FOREIGN KEY (org_id, added_by)  REFERENCES memberships (org_id, id)
);

-- =============================================================================
-- 7. Calendar
-- =============================================================================

CREATE TABLE events (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id      uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  title       text NOT NULL CHECK (length(btrim(title)) BETWEEN 1 AND 200),
  description text CHECK (length(description) <= 5000),
  location    text CHECK (length(location) <= 200),
  -- Exactly one shape: timed (instants) or all-day (dates). All-day events are
  -- dates so "2 Nov" stays 2 Nov in every time zone.
  starts_at   timestamptz,
  ends_at     timestamptz,
  start_date  date,
  end_date    date,
  audience    text NOT NULL DEFAULT 'org' CHECK (audience IN ('org', 'targeted')),
  created_by  uuid NOT NULL,
  version     integer NOT NULL DEFAULT 1,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (org_id, id),
  CHECK (
    (starts_at IS NOT NULL AND ends_at IS NOT NULL AND start_date IS NULL AND end_date IS NULL AND ends_at > starts_at)
    OR
    (starts_at IS NULL AND ends_at IS NULL AND start_date IS NOT NULL AND end_date IS NOT NULL AND end_date >= start_date)
  ),
  FOREIGN KEY (org_id, created_by) REFERENCES memberships (org_id, id)
);
CREATE INDEX events_timed_idx  ON events USING gist (org_id, tstzrange(starts_at, ends_at)) WHERE starts_at IS NOT NULL;
CREATE INDEX events_allday_idx ON events USING gist (org_id, daterange(start_date, end_date, '[]')) WHERE start_date IS NOT NULL;

CREATE TABLE event_audiences (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id        uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  event_id      uuid NOT NULL,
  department_id uuid,
  team_id       uuid,
  membership_id uuid,
  CHECK (num_nonnulls(department_id, team_id, membership_id) = 1),
  UNIQUE NULLS NOT DISTINCT (event_id, department_id, team_id, membership_id),
  FOREIGN KEY (org_id, event_id)      REFERENCES events (org_id, id)      ON DELETE CASCADE,
  FOREIGN KEY (org_id, department_id) REFERENCES departments (org_id, id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, team_id)       REFERENCES teams (org_id, id)       ON DELETE CASCADE,
  FOREIGN KEY (org_id, membership_id) REFERENCES memberships (org_id, id) ON DELETE CASCADE
);
CREATE INDEX event_audiences_team_idx   ON event_audiences (org_id, team_id) WHERE team_id IS NOT NULL;
CREATE INDEX event_audiences_dept_idx   ON event_audiences (org_id, department_id) WHERE department_id IS NOT NULL;
CREATE INDEX event_audiences_member_idx ON event_audiences (org_id, membership_id) WHERE membership_id IS NOT NULL;

-- =============================================================================
-- 8. Announcements
-- =============================================================================

CREATE TABLE announcements (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id     uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  author_id  uuid NOT NULL,
  title      text NOT NULL CHECK (length(btrim(title)) BETWEEN 1 AND 200),
  body       text NOT NULL CHECK (length(btrim(body)) BETWEEN 1 AND 20000),
  audience   text NOT NULL DEFAULT 'org' CHECK (audience IN ('org', 'targeted')),
  is_pinned  boolean NOT NULL DEFAULT false,
  publish_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz,
  version    integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (org_id, id),
  CHECK (expires_at IS NULL OR expires_at > publish_at),
  FOREIGN KEY (org_id, author_id) REFERENCES memberships (org_id, id)
);
CREATE INDEX announcements_feed_idx ON announcements (org_id, publish_at DESC);

CREATE TABLE announcement_audiences (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id          uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  announcement_id uuid NOT NULL,
  department_id   uuid,
  team_id         uuid,
  membership_id   uuid,
  CHECK (num_nonnulls(department_id, team_id, membership_id) = 1),
  UNIQUE NULLS NOT DISTINCT (announcement_id, department_id, team_id, membership_id),
  FOREIGN KEY (org_id, announcement_id) REFERENCES announcements (org_id, id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, department_id)   REFERENCES departments (org_id, id)   ON DELETE CASCADE,
  FOREIGN KEY (org_id, team_id)         REFERENCES teams (org_id, id)         ON DELETE CASCADE,
  FOREIGN KEY (org_id, membership_id)   REFERENCES memberships (org_id, id)   ON DELETE CASCADE
);

CREATE TABLE announcement_reads (
  org_id          uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  announcement_id uuid NOT NULL,
  membership_id   uuid NOT NULL,
  read_at         timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (announcement_id, membership_id),
  FOREIGN KEY (org_id, announcement_id) REFERENCES announcements (org_id, id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, membership_id)   REFERENCES memberships (org_id, id)   ON DELETE CASCADE
);
CREATE INDEX announcement_reads_member_idx ON announcement_reads (org_id, membership_id);

CREATE TABLE announcement_attachments (
  org_id          uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  announcement_id uuid NOT NULL,
  file_id         uuid NOT NULL,
  added_at        timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (announcement_id, file_id),
  FOREIGN KEY (org_id, announcement_id) REFERENCES announcements (org_id, id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, file_id)         REFERENCES files (org_id, id)
);

-- =============================================================================
-- 9. Platform: notifications, activity log, outbox, idempotency
-- =============================================================================

CREATE TABLE notifications (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id          uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  recipient_id    uuid NOT NULL,
  kind            text NOT NULL CHECK (kind ~ '^[a-z]+(\.[a-z_]+)+$'),   -- e.g. leave.approved
  title           text NOT NULL CHECK (length(title) <= 200),
  body            text CHECK (length(body) <= 1000),
  entity_type     text,
  entity_id       uuid,
  -- Outbox event id, or a deterministic id for cron reminders. Makes retries harmless.
  source_event_id uuid NOT NULL,
  read_at         timestamptz,
  emailed_at      timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now(),
  UNIQUE (source_event_id, recipient_id),
  CHECK ((entity_type IS NULL) = (entity_id IS NULL)),
  FOREIGN KEY (org_id, recipient_id) REFERENCES memberships (org_id, id) ON DELETE CASCADE
);
CREATE INDEX notifications_inbox_idx  ON notifications (org_id, recipient_id, created_at DESC);
CREATE INDEX notifications_unread_idx ON notifications (org_id, recipient_id) WHERE read_at IS NULL;

CREATE TABLE notification_preferences (
  org_id        uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  membership_id uuid NOT NULL,
  kind          text NOT NULL,
  in_app        boolean NOT NULL DEFAULT true,
  email         boolean NOT NULL DEFAULT true,
  PRIMARY KEY (membership_id, kind),
  FOREIGN KEY (org_id, membership_id) REFERENCES memberships (org_id, id) ON DELETE CASCADE
);

CREATE TABLE activity_events (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id      uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  actor_id    uuid,                             -- NULL = system
  entity_type text NOT NULL CHECK (entity_type IN (
                'organization', 'membership', 'invitation', 'department', 'team',
                'leave_type', 'holiday', 'leave_request', 'task', 'ticket',
                'event', 'announcement', 'file')),
  entity_id   uuid NOT NULL,
  action      text NOT NULL CHECK (action ~ '^[a-z_]+$'),
  changes     jsonb NOT NULL DEFAULT '{}'::jsonb,   -- {"status": ["todo", "in_progress"]}
  request_id  text,                                -- correlates with API logs
  created_at  timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (org_id, actor_id) REFERENCES memberships (org_id, id)
);
CREATE INDEX activity_events_entity_idx ON activity_events (org_id, entity_type, entity_id, created_at DESC);
CREATE INDEX activity_events_org_idx    ON activity_events (org_id, created_at DESC);
CREATE TRIGGER activity_events_append_only BEFORE UPDATE ON activity_events
  FOR EACH ROW EXECUTE FUNCTION forbid_update();

-- Idempotency for scheduled work. A cron job claims (org, job, period) with
-- INSERT ... ON CONFLICT DO NOTHING and only runs when the insert succeeded, so
-- retries, worker restarts and overlapping ticks never repeat a run.
-- period_key is computed in the org's time zone, e.g. '2026-10-12' for a daily
-- reminder or '2026' for yearly accrual, which also makes DST shifts harmless.
CREATE TABLE scheduled_runs (
  org_id       uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  job_name     text NOT NULL CHECK (job_name ~ '^[a-z]+(\.[a-z_]+)+$'),   -- e.g. tasks.due_reminder
  period_key   text NOT NULL CHECK (length(period_key) BETWEEN 4 AND 32),
  started_at   timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  PRIMARY KEY (org_id, job_name, period_key)
);

CREATE TABLE outbox_events (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id     uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  event_type text NOT NULL CHECK (event_type ~ '^[a-z]+(\.[a-z_]+)+$'),
  payload    jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  sent_at    timestamptz,
  attempts   integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  last_error text
);
-- The relay claims with: SELECT ... WHERE sent_at IS NULL ORDER BY created_at
--                        LIMIT 100 FOR UPDATE SKIP LOCKED
CREATE INDEX outbox_events_unsent_idx ON outbox_events (created_at) WHERE sent_at IS NULL;

CREATE TABLE idempotency_keys (
  org_id              uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  membership_id       uuid NOT NULL,
  idem_key            text NOT NULL CHECK (length(idem_key) BETWEEN 8 AND 128),
  request_fingerprint bytea NOT NULL,           -- hash of method + path + body; reuse with a different body = 422
  status              text NOT NULL DEFAULT 'in_progress' CHECK (status IN ('in_progress', 'completed')),
  response_status     smallint,
  response_body       jsonb,
  created_at          timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (membership_id, idem_key),
  CHECK (status = 'in_progress' OR response_status IS NOT NULL),
  FOREIGN KEY (org_id, membership_id) REFERENCES memberships (org_id, id) ON DELETE CASCADE
);
CREATE INDEX idempotency_keys_expiry_idx ON idempotency_keys (created_at);  -- 24 h cleanup

-- =============================================================================
-- 10. updated_at triggers
-- =============================================================================

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'users', 'organizations', 'departments', 'memberships', 'teams',
    'leave_types', 'leave_requests', 'tasks', 'ticket_categories', 'tickets',
    'events', 'announcements'
  ] LOOP
    EXECUTE format(
      'CREATE TRIGGER %I BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION set_updated_at()',
      t || '_updated_at', t);
  END LOOP;
END $$;

-- =============================================================================
-- 11. Row-level security
-- =============================================================================

ALTER TABLE organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE organizations FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON organizations
  USING (id = app_org_id()) WITH CHECK (id = app_org_id());

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'departments', 'memberships', 'teams', 'team_members', 'invitations', 'org_counters',
    'files',
    'leave_types', 'holidays', 'leave_requests', 'leave_request_allocations', 'leave_ledger', 'leave_request_attachments',
    'tasks', 'task_comments', 'task_attachments',
    'ticket_categories', 'tickets', 'ticket_comments', 'ticket_attachments',
    'events', 'event_audiences',
    'announcements', 'announcement_audiences', 'announcement_reads', 'announcement_attachments',
    'notifications', 'notification_preferences', 'activity_events', 'scheduled_runs', 'outbox_events', 'idempotency_keys'
  ] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format(
      'CREATE POLICY tenant_isolation ON %I USING (org_id = app_org_id()) WITH CHECK (org_id = app_org_id())', t);
  END LOOP;
END $$;

-- Guard: fail the migration if any table with org_id lacks RLS.
DO $$
DECLARE missing text;
BEGIN
  SELECT string_agg(c.relname, ', ') INTO missing
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = 'public'
  JOIN pg_attribute a ON a.attrelid = c.oid AND a.attname = 'org_id' AND NOT a.attisdropped
  WHERE c.relkind = 'r' AND NOT (c.relrowsecurity AND c.relforcerowsecurity);
  IF missing IS NOT NULL THEN
    RAISE EXCEPTION 'tenant tables without forced RLS: %', missing;
  END IF;
END $$;

-- Narrow cross-tenant reads for the signed-in user, so the API never needs a
-- role that bypasses RLS. They apply only in user context (app.user_id set,
-- no org chosen yet) and are read-only; once app.org_id is set, a session sees
-- strictly that org, so a forgotten org filter still cannot leak other orgs.
--   * a user sees their own memberships in every org (login, org switcher,
--     and the tenant plugin's membership check before app.org_id is set)
--   * a user sees the organizations they belong to
CREATE POLICY own_memberships ON memberships FOR SELECT
  USING (app_org_id() IS NULL AND user_id = app_user_id());
CREATE POLICY member_organizations ON organizations FOR SELECT
  USING (app_org_id() IS NULL
         AND EXISTS (SELECT 1 FROM memberships m
                     WHERE m.org_id = organizations.id AND m.user_id = app_user_id()));

-- =============================================================================
-- 12. Privileges
-- =============================================================================

GRANT USAGE ON SCHEMA public TO opsflow_app, opsflow_worker;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO opsflow_app, opsflow_worker;
-- Append-only and lifecycle-sensitive tables.
REVOKE UPDATE, DELETE ON leave_ledger, activity_events FROM opsflow_app, opsflow_worker;
-- Org creation stays under RLS: the API sets app.org_id to the new org's id
-- before inserting it. Org deletion is a worker job.
REVOKE DELETE ON organizations FROM opsflow_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO opsflow_app, opsflow_worker;

COMMIT;
